### ISSUE TITLE
Add instructions how to contribute to group projects

### ISSUE THREAD

**Issue by lahoffm** [lahoffm/github_help#1]
Currently the most common commands you would use to contribute to group projects are in uncompleted draft form at bottom of [README.md](https://github.com/lahoffm/github_help/blob/master/README.md). That needs to be completed. 

More importantly, [my powerpoint](https://github.com/lahoffm/github_help/blob/master/Github%20introduction%20Lukas.pptx) doesn't have a walkthrough for using `git remote/fetch/merge/push/pull/tag/...` with a demo remote group project.

**Comment by lahoffm** [comment]
The best option would be to have commands listed in a typical pipeline from pulling their repo to submitting a pull request, as I already sort of did in the draft. Then Issue #2 can help with how to work with pull requests once they're submitted and people start to review them.

**Comment by NickleDave** [comment]
Good outline here:
https://github.com/amueller/talks_odt/raw/master/2017/scikit-learn-sprint-instructions.pdf
And there's a lot of good info in the "Contributing" pages for scikit-learn/scipy/numpy
http://scikit-learn.org/stable/developers/contributing.html
https://docs.scipy.org/doc/numpy/dev/

**Comment by lahoffm** [comment]
Added David's links to [README.md](https://github.com/lahoffm/github_help/blob/master/README.md).

Added walkthrough to [README.md](https://github.com/lahoffm/github_help/blob/master/README.md) for contributing to group projects in a "fork-merge" model.

Maybe someone could add a walkthrough of a different way to contribute to a group project if they encounter it?

**Comment by lahoffm** [comment]
Closing this issue because we have the basic information in the README, not sure if worth putting it in powerpoint too.
